<?= $this->fetch('header.phtml') ?>
<form method="POST" action="/tickets">
  <input type="hidden" name="csrf_name" value="<?=$csrf_name ?>">
  <input type="hidden" name="csrf_value" value="<?=$csrf_value ?>">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">チケット作成</h2>
      <div class="card-text">
        <div class="form-group">
          <label for="subject">件名</label>
          <input type="text" name="subject" id="subject" class="form-control">
            <?php if (isset($errors)) : ?>
              <ul>
                  <?php foreach ($errors['subject'] as $error): ?>
                    <li><?= $error ?></li>
                  <?php endforeach; ?>
              </ul>
            <?php endif; ?>
        </div>
      </div>
    </div>
    <div class="card-body">
      <button class="btn btn-primary">作成</button>
    </div>
  </div>
</form>
<?= $this->fetch('footer.phtml') ?>
